# Generated by Django 3.0.5 on 2022-09-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='sizes',
            new_name='age',
        ),
        migrations.AddField(
            model_name='details',
            name='diabetes',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=5),
        ),
        migrations.AddField(
            model_name='details',
            name='disease',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=5),
        ),
        migrations.AddField(
            model_name='details',
            name='tattoo',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=5),
        ),
    ]
