# Generated by Django 3.0.5 on 2022-09-24 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0006_remove_donor_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
    ]
