# Generated by Django 3.0.5 on 2022-10-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0009_remove_donor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
