# Generated by Django 3.0.5 on 2022-09-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='certificate',
            field=models.ImageField(null=True, upload_to='profile_pic/Certificate/'),
        ),
    ]
