# Generated by Django 3.0.5 on 2022-09-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='certificate',
            field=models.ImageField(null=True, upload_to='static/profile_pic/Certificate/'),
        ),
    ]
