# Generated by Django 3.0.5 on 2022-10-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_bloodrequest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='certificate',
            field=models.ImageField(null=True, upload_to='static/profile_pic/Certificate/'),
        ),
    ]
