# Generated by Django 3.0.5 on 2022-10-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_bloodrequest_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='certificate',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
