# Generated by Django 3.0.5 on 2022-10-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0007_remove_bloodrequest_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='updates',
            field=models.CharField(choices=[('Urgent', 'Urgent'), ('Not Urgent', 'Not Urgent')], default='Not Urgent', max_length=255),
        ),
    ]
